
---
aleph:
  port:
    oauth: 18080
    finance: 18090
    media: 18100
    acquisitions: 18110
    adsales: 18120
    contentdelivery: 18130
    depreciation: 18140
    entities: 18150
    prebilling: 18160
    programming: 18170
    titles: 18180
    config: 18190
    branding: 18200
    log: 18220
    support: 18230
    placer: 18240
    eip: 18250
    clearproxy: 8080
    commondb: 1521

  frontport:
    oauth: 18082
    finance: 18092
    media: 18102
    acquisitions: 18112
    adsales: 18122
    contentdelivery: 18132
    depreciation: 18142
    entities: 18152
    prebilling: 18162
    programming: 18172
    titles: 18182
    branding: 18202
    log: 18222
    support: 18232
    placer: 18242

  db:
    host: db.turner.dev.redb.ee
    sid: ALEPHDBD1

  oauth:
    context-path: /aleph-oauth
    uri: http://argalephdockerd1:${aleph.port.oauth}${aleph.oauth.context-path}
    redis:
      enabled: false
      host: localhost
      port: 6379

  support:
    context-path: /support
    api-path: /api/v1
    uri: http://argalephdockerd1:${aleph.port.support}${aleph.support.context-path}

  programming:
    context-path: /programming
    api-path: /api/v1
    uri: http://argalephdockerd1:${aleph.port.programming}${aleph.programming.context-path}

  media:
    context-path: /media
    api-path: /api/v1
    uri: http://argalephdockerd1:${aleph.port.media}${aleph.media.context-path}

  log:
    context-path: /log
    api-path: /api/v1
    uri: http://argalephdockerd1:${aleph.port.log}${aleph.log.context-path}

  clearproxy:
    base: http://argalephdockerd1:${aleph.port.clearproxy}
    context-path: /PFT.Clear.TurnerTracker
    api-path-tvc: /TurnerLatam.svc/json
    api-path-longform: Longform/longformService/staging/v1
    uri: ${aleph.clearproxy.base}${aleph.clearproxy.context-path}

  adsales:
    context-path: /adsales
    api-path: /api/v1
    uri: http://argalephdockerd1:${aleph.port.adsales}${aleph.adsales.context-path}

  placer:
    context-path: /placer
    api-path: /api/v1
    uri: http://argalephdockerd1:${aleph.port.placer}${aleph.placer.context-path}

  orders:
    context-path: /orders
    api-path: /api/v1
    uri: http://argalephdockerd1:${aleph.port.orders}${aleph.orders.context-path}


---
feign:
   hystrix:
     enabled: true
ribbon:
  eureka:
        enabled: false
  ConnectTimeout: 30000
  ReadTimeout: 300000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
             maxConcurrentRequests: 200
        timeout:
          enabled: false
---
ldap:
  url: ldap://argtbsdc01.turner.com:389
  mocked: false
  host: turner.com

---
spring:
  datasource:
    url: jdbc:oracle:thin:@argalephorad2.turner.com:1521:ALEPHD2
    username: proxy_mig
    password: proxy_mig
    driver-class-name: oracle.jdbc.driver.OracleDriver
    pool-name: SpringBootHikariCP
    type: com.zaxxer.hikari.HikariDataSource
    leakDetectionThreshold: 2500
    maximumPoolSize: 30
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle9Dialect

  oauth2:
    resource:
      userInfoUri: ${aleph.oauth.uri}/user
  auth:
    serverurl: ${aleph.oauth.uri}/oauth/check_token
---

security:
  oauth2:
     resource:
       user-info-uri: ${aleph.oauth.uri}/user
       token-info-uri: ${aleph.oauth.uri}/oauth/check_token
       filter-order: 3


---
management:
  security:
    enabled: false
  context-path: /manage

encrypt:
  key: turner
