
---
aleph:
  port:
    oauth: 18080
    finance: 18090
    media: 18100
    rights: 18110
    adsales: 18120
    adsales-freetv: 18121
    contentdelivery: 18130
    depreciation: 18140
    entities: 18150
    prebilling: 18160
    programming: 18170
    title: 18180
    config: 18190
    branding: 18200
    log: 18220
    support: 18230
    placer: 18240
    eip-mam: 18250
    eip-emea: 18251
    eip-internal: 18252
    eip-external: 18253
    clearproxy: 8080
    commondb: 1521
    orders: 18260
    vod: 18270

  frontport:
    oauth: 18082
    finance: 18092
    media: 18102
    rights: 18112
    adsales: 18122
    adsales-freetv: 18123
    contentdelivery: 18132
    depreciation: 18142
    entities: 18152
    prebilling: 18162
    programming: 18172
    title: 18182
    branding: 18202
    log: 18222
    support: 18232
    placer: 18242
    orders: 18262
    vod: 18272
    
  db:
    host: db.turner.dev.redb.ee
    sid: ALEPHDBD1imumI
    
  redis:
    host: argalephdockerprod1
    
  oauth:
    context-path: /aleph-oauth
    uri: https://oauth.aleph.turner.com
    redis:
      enabled: true
      host: argalephdockerprod1
      port: 6379

  title:
    context-path: /title
    api-path: /api/v1
    uri: http://title.aleph.turner.com${aleph.title.context-path}

  support:
    context-path: /support
    api-path: /api/v1
    uri: http://support.aleph.turner.com${aleph.support.context-path}

  media:
    context-path: /media
    api-path: /api/v1
    uri: http://media.aleph.turner.com${aleph.media.context-path}

  log:
    context-path: /log
    api-path: /api/v1
    uri: http://log.aleph.turner.com${aleph.log.context-path}

  branding:
    context-path: /branding
    api-path: /api/v1
    uri: http://branding.aleph.turner.com${aleph.branding.context-path}

  clearproxy:
    base: http://argalephdockerprod2:${aleph.port.clearproxy}
    context-path: /PFT.Clear.TurnerTracker
    api-path-tvc: Prod/TurnerLatam.svc/json
    api-path-longform: Longform/longformService/v1
    api-path-vod: ${aleph.clearproxy.base}/PFT.Clear.API/workorder
    uri: ${aleph.clearproxy.base}${aleph.clearproxy.context-path}

  programming:
    context-path: /programming
    api-path: /api/v1
    uri: http://programming.aleph.turner.com${aleph.programming.context-path}

  adsales:
    context-path: /adsales
    api-path: /api/v1
    uri: http://adsales.aleph.turner.com${aleph.adsales.context-path}

  adsales-freetv:
    context-path: /adsales
    api-path: /api/v1
    uri: http://freetv.aleph.turner.com${aleph.adsales-freetv.context-path}

  placer:
    context-path: /placer
    api-path: /api/v1
    uri: http://placer.aleph.turner.com${aleph.placer.context-path}

  orders:
    context-path: /orders
    api-path: /api/v1
    uri: http://orders.aleph.turner.com${aleph.orders.context-path}

  vod:
    context-path: /vod
    api-path: /api/v1
    uri: http://vod.aleph.turner.com${aleph.vod.context-path} 

  prebilling:
    context-path: /prebilling
    api-path: /api/v1
    uri: http://prebilling.aleph.turner.com${aleph.prebilling.context-path}

  officeMail:
    uri: http://argalephdockerprod2:${aleph.port.officeService}

  predictive:
    programming:
      uri: http://argalephdockerppp:19300/


---
feign:
   hystrix:
     enabled: true
ribbon:
  eureka:
        enabled: false
  ConnectTimeout: 30000
  ReadTimeout: 300000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
             maxConcurrentRequests: 300
        timeout:
             enabled: false
---
ldap:
  url: ldap://argtbsdc01.turner.com:389
  mocked: false
  host: turner.com

---
mail:
  server:
    host: getsmtp.turner.com
    port: 25

---
spring:
  datasource:
    url: jdbc:oracle:thin:@argalephdbprod.turner.com:1530/ALEPHPR_SERVICE.turner.com
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: proxy
    password: '{cipher}1711c7ab1c1c70c07be977589370fe2e057ebe9c3d032d86e654715179cd2485'
    pool-name: SpringBootHikariCP
    type: com.zaxxer.hikari.HikariDataSource
    pool-prepared-statements: true
    max-open-prepared-statements: 500
    leakDetectionThreshold: 2500
    maximumPoolSize: 45
    maxLifetime: 2000000
    connectionTimeout: 30000

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle9Dialect

  data:
    elasticsearch:
      cluster-nodes: argalephdockerprod3:9300

  oauth2:
    resource:
      userInfoUri: ${aleph.oauth.uri}/user
  auth:
    serverurl: ${aleph.oauth.uri}/oauth/check_token

security:
  oauth2:
     resource:
       user-info-uri: ${aleph.oauth.uri}/user
       token-info-uri: ${aleph.oauth.uri}/oauth/check_token
       filter-order: 3

---
management:
  security:
    enabled: false
  context-path: /manage

server:
  tomcat:
    accessLogEnabled: true
    basedir: /log
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Real-IP
